version: '3.8'

services:
  oj-backend:
    build:
      context: ./oj-backend
      dockerfile: Dockerfile
    environment:
      - MYSQL_URL=jdbc:mysql://172.23.233.31:3306/oj-database?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      - MYSQL_USER=binzc
      - MYSQL_PASSWORD=20040713bzc
      - CODESANDBOX_URL=http://oj-sandbox/8122/api/code/executeCode
    volumes:
      - /home/binzc/service-data/static:/app/static
    ports:
      - "8121:8121"
    networks:
      - oj-network

  oj-frontend:
    build:
      context: ./oj-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - oj-backend
    networks:
      - oj-network

  oj-sandbox:
    build:
      context: ./oj-sandbox
      dockerfile: Dockerfile
    ports:
      - "8122:8122"
    volumes:
      - /home/binzc/service-data/temp:/app/temp
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - oj-network

networks:
  oj-network:
    driver: bridge
