version: '3.8'

services:
  oj-backend:
    build:
      context: ./oj-backend
      dockerfile: Dockerfile
    environment:
      - MYSQL_URL=jdbc:mysql://host.docker.internal:3306/oj-database?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      - MYSQL_USER=root
      - MYSQL_PASSWORD=20040713bzc
    volumes:
      - /home/binzc/service-data/static:/app/static
    ports:
      - "8121:8121"
    networks:
      - oj-network

  oj-frontend:
    image: nginx:1.25
    volumes:
      - ./oj-frontend/dist:/usr/share/nginx/html
      - ./oj-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - oj-backend
    networks:
      - oj-network

  oj-sandbox:
    build:
      context: ./oj-sandbox
      dockerfile: Dockerfile
    ports:
      - "8122:8122"
    volumes:
      - /home/binzc/service-data/temp:/app/temp
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - oj-network

networks:
  oj-network:
    driver: bridge
