server:
  address: localhost
  port: 8121
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oj-database
    username: root
    password: 20040713bzc
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
